### ISSUE TITLE
Checkbox component

### ISSUE THREAD

**Issue by germain-gg** [element-hq/compound#121]
### Component name

_Checkbox_

### Figma link

_[Figma link](https://www.figma.com/file/rTaQE2nIUSLav4Tg3nozq7/Compound-Web-Components?type=design&node-id=129%3A4461&t=HGT5cgdioi0q7IjF-1)_

```[tasklist]
# Design phase
- [x] Add <component name> Web, iOS & Android variant drafts to Compound Figma documents
- [x] Create new tokens for <component name>
- [x] Release <component name> styles
- [x] Review <component name> web implementation & publish in shared Figma library  
- [ ] Review <component name> mobile implementation & publish in shared Figma library  
- [ ] https://github.com/vector-im/compound/issues/176
```

```[tasklist]
# Development phase
- [x] Implement Radio component on Web
- [ ] https://github.com/vector-im/compound/issues/168
- [ ] Implement <component name> on iOS
```
