### ISSUE TITLE
ActionControl component

### ISSUE THREAD

**Issue by germain-gg** [element-hq/compound#126]
### Component name

_ActionControl_

A generic component to be able to associate an account with an input. Useful to implement a password reveal component or a way to copy the input value.

### Figma link

_[Figma link](https://www.figma.com/file/HUysJAhv6cK6p1Pc81Fxaa/Matrix-Authentication-Service-(MAS)?type=design&node-id=101%3A16968&t=GVGj9Wfqu0glyKXn-1)_

```[tasklist]
# Design phase
- [ ] Add <component name> Web, iOS & Android variant drafts to Compound Figma documents
- [ ] Create new tokens for <component name>
- [ ] Release <component name> styles
- [ ] Review <component name> web implementation & publish in shared Figma library  
- [ ] Review <component name> mobile implementation & publish in shared Figma library  
```

```[tasklist]
# Development phase
- [x] Implement <component name> on Web
- [ ] Implement <component name> on Android
- [ ] Implement <component name> on iOS
```
