### ISSUE TITLE
Create ActionButton 

### ISSUE THREAD

**Issue by germain-gg** [element-hq/compound#147]
### Component name

_ActionButton_

### Figma link

_[Figma link](https://www.figma.com/file/wqgXVb7RVaIybfRsXdWEiL/Trust-%26-Decoration?type=design&node-id=837%3A53617&t=0Pho32KexIdktvph-1)_

```[tasklist]
# Design phase
- [ ] Add <component name> Web, iOS & Android variant drafts to Compound Figma documents
- [ ] Create new tokens for ActionButton
- [ ] Release ActionButton styles
- [ ] Review ActionButton web implementation & publish in shared Figma library  
- [ ] Review ActionButton mobile implementation & publish in shared Figma library  
```

```[tasklist]
# Development phase
- [x] Implement ActionButton on Web
- [ ] Implement ActionButton on Android
- [ ] Implement ActionButton on iOS
```
