### ISSUE TITLE
ExpandableParagraph

### ISSUE THREAD

**Issue by germain-gg** [element-hq/compound#149]
### Component name

_ExpandableParagrah_

### Figma link

_[Figma link](https://www.figma.com/file/wqgXVb7RVaIybfRsXdWEiL/Trust-%26-Decoration?type=design&node-id=837%3A53617&t=0Pho32KexIdktvph-1)_

```[tasklist]
# Design phase
- [ ] Add ExpandableParagrah Web, iOS & Android variant drafts to Compound Figma documents
- [ ] Create new tokens for ExpandableParagrah
- [ ] Release ExpandableParagrah styles
- [ ] Review ExpandableParagrah web implementation & publish in shared Figma library  
- [ ] Review ExpandableParagrah mobile implementation & publish in shared Figma library  
```

```[tasklist]
# Development phase
- [ ] Implement ExpandableParagrah on Web
- [ ] Implement ExpandableParagrah on Android
- [ ] Implement ExpandableParagrah on iOS
```
