### ISSUE TITLE
MenuItem

### ISSUE THREAD

**Issue by germain-gg** [element-hq/compound#150]
### Component name

_MenuItem_

### Figma link

_[Figma link](https://www.figma.com/file/wqgXVb7RVaIybfRsXdWEiL/Trust-%26-Decoration?type=design&node-id=837%3A53617&t=0Pho32KexIdktvph-1)_

```[tasklist]
# Design phase
- [ ] Add MenuItem Web, iOS & Android variant drafts to Compound Figma documents
- [ ] Create new tokens for MenuItem
- [ ] Release MenuItem styles
- [ ] Review MenuItem web implementation & publish in shared Figma library  
- [ ] Review MenuItem mobile implementation & publish in shared Figma library  
```

```[tasklist]
# Development phase
- [ ] Implement MenuItem on Web
- [ ] Implement MenuItem on Android
- [ ] Implement MenuItem on iOS
```
