### ISSUE TITLE
Icon Button

### ISSUE THREAD

**Issue by janogarcia** [element-hq/compound#181]
**Figma link:** https://www.figma.com/file/G1xy0HDZKJf5TCRFmKb5d5/Compound-Android-Components?type=design&node-id=1182-48861&mode=design&t=QgGLVpi0ERJNFyCZ-11

```[tasklist]
### Design
- [ ] Components on Figma
- [ ] Component documentation on Figma
- [ ] Tested for theming
- [ ] Shareout for designers
```

```[tasklist]
### Tasks
- [ ] https://github.com/vector-im/compound/issues/279
```
