### ISSUE TITLE
Divider component

### ISSUE THREAD

**Issue by germain-gg** [element-hq/compound#254]
### Component name

_Divider_

### Figma link

- Web Figma document link: https://www.figma.com/file/rTaQE2nIUSLav4Tg3nozq7/Compound-Web-Components?type=design&node-id=2547-653&mode=design&t=BXODQNk2fu16eEcC-11
- iOS Figma document link: ...
- Android Figma document link: ...

```[tasklist]
# Design phase
- [ ] Design phase for Web
- [ ] Design phase for iOS
- [ ] Design phase for Android
```

```[tasklist]
# Development phase
- [ ] https://github.com/vector-im/compound-web/pull/113
- [ ] Development phase for iOS
- [ ] Development phase for Android
```
